
---
string                  simulation_name
int64	                no_drones
geometry_msgs/Point[]   target_positions
float64[]               target_thresholds
float64                 aoi_weight
float64                 violation_weight
float64                 fairness_weight
int64                   simulation_time

geometry_msgs/Vector3   wind_vector

float64[]               last_visits
